# Required image settings for OpenTelemetry Collector Helm chart
image:
  repository: otel/opentelemetry-collector
  tag: "0.99.0"
# Override values for OpenTelemetry Collector Helm chart
mode: deployment
config:
  exporters:
    otlp:
      endpoint: "host.docker.internal:4317"
      tls:
        insecure: true
  service:
    pipelines:
      traces:
        receivers: [otlp]
        exporters: [otlp]
      metrics:
        receivers: [otlp]
        exporters: [otlp]
      logs:
        receivers: [otlp]
        exporters: [otlp]
